version: '3'

services:
  pg:
    image: postgres:15-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: urlSecure
    ports:
      - '5432:5432'
    volumes:
      - ./tmp/db-data:/var/lib/postgresql/data
    networks:
      - app_network

  app:
    container_name: app
    depends_on:
      - pg
    build:
      context: .
      dockerfile: ./docker/dev/app/Dockerfile
    environment:
      NODE_ENV: development
      PORT: 3000
      DB_HOST: pg
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: urlSecure
      DB_LOGS: false
    volumes:
      - ./:/app
      - ./node_modules:/app/node_modules
    ports:
      - 3000:3000
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
